name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Adjust based on your frontend Node.js version

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build project
        run: cd frontend && npm run build

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" | base64 -d > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          scp -i /tmp/id_rsa -o StrictHostKeyChecking=no -r frontend/build/* $USER@$HOST:/home/ubuntu/frontend/
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            sudo cp -r /home/ubuntu/frontend/* /var/www/html/
          EOF
